replicaCount: 1
namespace: prod
environment: prod
image:
  repository: us-east1-docker.pkg.dev/microdrive-dev/influencer-website/iw
  tag: dev-984
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: growripple.ai
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - growripple.ai
      secretName: prod-growripple.ai-tls

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    memory: "600Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"


env:
- name: VUE_APP_API_URL
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: VUE_APP_API_URL
- name: ADMIN_EMAIL
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: ADMIN_EMAIL
- name: MAILGUN_API_KEY
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: MAILGUN_API_KEY
- name: MAILGUN_DOMAIN
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: MAILGUN_DOMAIN
- name: MAILGUN_FROM
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: MAILGUN_FROM
- name: ZOHO_CLIENT_ID
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: ZOHO_CLIENT_ID
- name: ZOHO_CLIENT_SECRET
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: ZOHO_CLIENT_SECRET
- name: ZOHO_REFRESH_TOKEN
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: ZOHO_REFRESH_TOKEN
- name: ZOHO_CALENDAR_ID
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: ZOHO_CALENDAR_ID
- name: ZOHO_REGION
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: ZOHO_REGION
- name: ZOHO_ENABLE_MEETING
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: ZOHO_ENABLE_MEETING
- name: ZOHO_ORGANIZATION_ID
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: ZOHO_ORGANIZATION_ID
- name: ZOHO_PRESENTER_ZUID
  valueFrom:
    secretKeyRef:
      name: my-multi-key-secret
      key: ZOHO_PRESENTER_ZUID