replicaCount: 1
namespace: prod
environment: prod
image:
  repository: us-east1-docker.pkg.dev/microdrive-dev/influencer-website/iw
  tag: dev-984
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "web"   # ensure port 80
    traefik.ingress.kubernetes.io/router.priority: "1"
  hosts:
    - host: growripple.ai
      paths:
        - path: /.well-known/acme-challenge/*
          pathType: Prefix
          backend:
            service:
              name: cm-acme-http-solver-76z7m
              port:
                number: 8089
        - path: /*
          pathType: Prefix
  tls:
    - hosts:
        - growripple.ai
      secretName: growripple.ai-tls

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    memory: "600Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
